apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: debugme
  name: debugme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugme
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debugme
    spec:
      containers:
        - image: docker.io/hamzablm/debugme:0.0.1-SNAPSHOT
          name: debugme
          resources: {}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: debug
              containerPort: 5005
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
